Rsvp form page
bitly/sprinterns2024 pull request #18
Opened 2024-01-08 21:24 UTC by iden-a

2024-01-09 19:20 UTC, mclausen792 requested changes
Nice work! Just a couple little requests

2024-01-09 19:20 UTC, mclausen792 commented on views/js/evently/src/RSVPForm.jsx
> +        <>
The indentation in this file isn't consistent and it makes it a little hard to read. Can you fix it? I believe it should be like this 
```
<>
            <div className="create-rsvp">
                <div className='rsvp-form-container'>
                    <form className='rsvp-form' onSubmit={handleRSVPSubmit}>
                        <h2 className='rsvp-title'> 
                        Register for "Event Name" 
                        </h2>

                        <div className="eventid-rsvp-container">
                            <div className='eventId'>
                                <label> Event ID: </label>
                                <input type="number" className = "rsvp-input-boxes" value={eventId} onChange={(e) => setEventId(e.target.value)} />
                            </div>

                            <div className='response-container'>
                                <label> RSVP: </label>
                                <select className = "rsvp-input-boxes" value={RSVPResponse} onChange={(e) => setRSVPResponse(e.target.value)}>
                                    <option name="yes" value="yes" > Yes </option>
                                    <option name="no" value="no" > No </option>
                                    <option name="maybe" value="maybe" > Maybe </option>
                                </select>
                            </div>
                        </div>

                        <div className='first-last-name-container'>
                            <div className='first-name'>
                                <label> First Name: </label>
                                <input type="text" className = "rsvp-input-boxes" value={firstName} onChange={(e) => setFirstName(e.target.value)} />
                            </div>

                            <div className='last-name'>
                                <label> Last Name: </label>
                                <input type="text" className = "rsvp-input-boxes" value={lastName} onChange={(e) => setLastName(e.target.value)} />
                            </div>
                        </div>

                        <div className="phone-email-container">
                            <div className='phone'>
                                <label> Phone #: </label>
                                <input type="text" className = "rsvp-input-boxes" value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} />
                            </div>

                            <div className='email'>
                                <label> Email: </label>
                                <input type="text" className = "rsvp-input-boxes" value={email} onChange={(e) => setEmail(e.target.value)} />
                            </div>
                        </div>


                        <button type='submit' className='rsvp-submit-btn'> Register</button>

                    </form>

                    {successMessage && (
                    <div role="alert" className="alert">
                        <div>{successMessage}</div>
                    </div>)}
                    {/* {errorMessage && (
                    <div role="alert" className="error-alert">
                    <div>{errorMessage}</div>
                    </div>)} */}
                </div>
            </div>
</>
```

2024-01-10 20:25 UTC, iden-a commented on views/js/evently/src/RSVPForm.jsx
> +        <>
Okay, I will update the file with these changes.

2024-01-10 21:20 UTC, mclausen792 approved these changes
Looks good, thanks for making those updates!

2024-01-10 21:36 UTC, merged